---
- name: stop container
  hosts: server
  gather_facts: no
  vars_files:
    - ../external_vars.yml
  tasks:
  - name: stop docker images
    ansible.builtin.shell:
      cmd: make stop
      chdir: "{{ work_dirr }}"
    register: out
  - debug: msg="{{ out.stdout }}"
